container:
  image: ruby:latest
  
rspec_task:
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: echo $RUBY_VERSION && cat Gemfile && cat *.gemspec
  install_script: bundle install
  rspec_script: bundle exec rspec
